repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: bitnami
  url: https://charts.bitnami.com/bitnami

---

{{- $ingressClass := "ingress" -}}

releases:
- name: ingress
  namespace: ingress
  chart: ingress-nginx/ingress-nginx
  values:
  - controller:
      ingressClass: {{ $ingressClass }}

- name: wordpress
  namespace: wordpress
  chart: bitnami/wordpress
  values:
  - ingress:
      enabled: true
      hostname: kubernetes.docker.internal
      annotations:
        kubernetes.io/ingress.class: {{ $ingressClass }}
