repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: bitnami
  url: https://charts.bitnami.com/bitnami

---

releases:
- name: ingress
  namespace: ingress
  chart: ingress-nginx/ingress-nginx
  values:
  - ingressClass: ingress

- name: wordpress
  namespace: wordpress
  chart: bitnami/wordpress
